#!/usr/bin/env ruby
# frozen_string_literal: true

require "simple_store_response"

def log(msg, level = "DEBUG")
  STDERR.write "[#{level}] #{msg}\n"
end

resp = SimpleStoreResponse.new(
  request_method: ENV["REQUEST_METHOD"],
  request_body: ARGF.read,
  filename: ENV["REMOTE_USER"],
  storage: "/var/tmp/simplestore"
)

begin
  resp.process_request!
rescue StandardError => e
  log e.message, "ERROR"
end

puts <<EOF
Status: #{resp.http_code}
Content-Type: #{resp.content_type}

#{resp.body}
EOF
