#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'

status = 'error'
debug = {}

def log(msg, level = 'DEBUG')
  STDERR.write "[#{level}] #{msg}\n"
end

if ENV['REQUEST_METHOD'] == 'POST'
  req_body = ARGF.read
  begin
    raise "Invalid parameters: '#{req_body}'." unless req_body.length > 0

    payload = JSON.parse(req_body, symbolize_names: true)

    File.open('message.json', 'w') do |f|
      f.write JSON.dump(payload)
    end
    status = 'ok'
  rescue StandardError => e
    log e.message, 'ERROR'
  end
end

puts <<EOF
Content-Type: application/json

{"status": "#{status}"}
EOF
